package-lock.json
package.json
src/App.vue
src/components/molecules/Ping.vue
src/components/molecules/study/CreateStudy.vue

createStudy API checked

---

src/components/molecules/study/CreateStudy.vue

create insert Test

---

package-lock.json
package.json
src/components/molecules/Footer.vue
src/components/molecules/member/Register.vue

20231114 routerLink

---

src/components/molecules/Header.vue
src/components/molecules/study/CreateStudy.vue

create category 출력중

---

src/components/molecules/study/CreateStudy.vue

create toggle 진행중

---

package-lock.json
package.json
src/cKEditor/UploadAdapter.js
src/components/molecules/study/CreateStudy.vue
src/components/molecules/study/SmartEditor.vue
src/main.js

F hyeon toggle

---

package-lock.json
package.json
src/App.vue
src/components/molecules/study/StudyView.vue
src/main.js
src/router/index.js

20231116 viewVue작업

---

src/components/molecules/study/StudyView.vue

20231117 studyView

---

src/assets/template/bacchusCss.css
src/assets/template/templatemo.css
src/components/molecules/study/CreateStudy.vue

party_count 진행중

---

src/components/molecules/study/CreateStudy.vue

study_member Limit DONE

---

src/components/molecules/study/CreateStudy.vue

create member added

---

src/components/molecules/study/CreateStudy.vue

thumb upload DONE

---

package-lock.json
package.json
src/App.vue
src/assets/template/dongil.css
src/components/molecules/study/ModifyStudy.vue
src/components/molecules/study/StudyView.vue
src/router/index.js

20231120 modify

---

src/components/molecules/study/ModifyStudy.vue
src/modules/study/StudyRecruitment.js

20231121 modify

---

src/components/molecules/common/Img.vue
src/components/molecules/study/StudyView.vue

20231121 img upload

---

html_template/study/studyView2.html
src/assets/template/bacchusCss.css
src/components/molecules/study/StudyView2.vue
src/router/index.js

20231123 view2

---

src/components/molecules/board/AccordionItem.vue
src/components/molecules/board/NoticeList.vue

cs 페이징만 남았다!!

---

src/assets/template/bacchusCss.css
src/assets/template/dongil.css
src/components/molecules/study/StudyView.vue
src/components/molecules/study/StudyView2.vue

20231123 view

---

src/components/molecules/board/AccordionItem.vue
src/components/molecules/board/CommunityList.vue
src/components/molecules/board/FaqList.vue
src/components/molecules/board/Tab.vue
src/components/molecules/study/CreateStudy.vue
src/components/molecules/study/ModifyStudy.vue
src/components/molecules/study/StudyView.vue

경로 재설정 및 테스트완료

---

package-lock.json
package.json
src/assets/template/templatemo.css
src/cKEditor/UploadAdapter.js
src/components/molecules/common/Carousel.vue
src/components/molecules/member/Register.vue
src/components/molecules/study/CreateStudy.vue
src/components/molecules/study/SmartEditor.vue
src/components/molecules/study/StudyView.vue
src/modules/study/StudyRecruitment.js
src/router/index.js
src/utils/validation.js

회원가입API 및 유효성 검사, 좋아요 기능 완료

---

src/components/molecules/board/CommunityWrite.vue

20231127 communityWrite

---

src/components/molecules/board/AccordionItem.vue
src/components/molecules/board/NoticeList.vue
src/components/molecules/member/Register.vue
src/components/molecules/study/StudyView.vue

유효성 검증 완벽히 DONE

---

src/components/molecules/study/ModifyStudy.vue
src/modules/study/StudyRecruitment.js

20231130 push

---

src/components/molecules/common/Header.vue
src/components/molecules/member/Register.vue

회원가입 이메일 인증번호 진행중

---

src/components/molecules/board/CommunityList.vue
src/components/molecules/board/CommunityView.vue
src/components/molecules/board/CommunityWrite.vue
src/router/index.js

20231201 communityView 기초작업

---

src/components/molecules/board/FaqList.vue
src/components/molecules/board/NoticeList.vue
src/components/molecules/board/Pagination.vue
src/components/molecules/common/Carousel.vue
src/components/molecules/common/Footer.vue
src/components/molecules/common/Header.vue
src/components/molecules/member/Register.vue
src/components/molecules/study/CreateStudy.vue
src/pages/Main.vue

전체적인 디자인 수정

---

package-lock.json
package.json
src/main.js

소셜 로그인 굿바이

---

src/pages/HyTestBed.vue
src/router/index.js

멤버 목록 업데이트 중

---

src/components/molecules/board/CommunityList.vue
src/components/molecules/board/CommunityModify.vue
src/components/molecules/board/CommunityView.vue
src/components/molecules/board/CommunityWrite.vue

20231206 modify 첨부파일 수정안됨 ㅠ

---

src/components/molecules/common/Header.vue
src/components/molecules/member/list/listform/MemberBox.vue
src/components/molecules/member/list/listform/MemberLocationButton.vue
src/pages/member/list/MemberList.vue
src/router/index.js
src/utils/fetch/memberFetch.js

멤버 리스트 디자인 100%

---

src/components/molecules/board/CommunityView.vue

누나랑 실험 하던 중 고쳤는데 어디가 바뀐 지 몰라서 일단 pr보냈습니다

community 수정 중 고쳤음

---

src/components/molecules/member/list/listform/MemberBox.vue
src/components/molecules/member/list/listform/MemberSearchInput.vue
src/components/molecules/member/list/listform/MemberSmallCate.vue
src/components/molecules/member/list/listform/MiddleContainer.vue
src/components/molecules/study/list/Paging.vue
src/pages/member/list/MemberList.vue
src/utils/fetch/memberFetch.js

파티원 검색 기능 끝
